#!/bin/bash

set -o nounset -o errexit

RUN=${XDG_RUNTIME_DIR-/run/user/$UID}/dot-nvim
mkdir -p "$RUN"
TMP=$(mktemp -d -p "$RUN" "run.XXXXX")
trap 'rm -rf $TMP' EXIT
chmod 0700 "$TMP"

printenv --null >"$TMP/outer.env"

ROOT=$(readlink -f "$0" | xargs dirname)

export NVIM_APPNAME=nvim
export NVIM_VERSION=${NVIM_VERSION-$(<"$ROOT/version")}

export DOT_NVIM_RUNTIME_DIR=$TMP
export DOT_NVIM_SNIPPETS="$ROOT/snippets"
export DOT_NVIM_SPELL="$ROOT/spell"

export XDG_CONFIG_HOME="$ROOT/config"
export XDG_DATA_HOME="$ROOT/share"
export XDG_STATE_HOME="$ROOT/state"

export NVIM_PYTHON_LOG_FILE="$XDG_STATE_HOME/$NVIM_APPNAME/python.log"

"$ROOT/root/$NVIM_VERSION/bin/nvim" "$@"
