#!/bin/bash

set -o nounset -o pipefail -o errexit

SCRIPT_DIR=$(readlink -f "$0" | xargs dirname)

export DOT_NVIM_ME=

#exec "$SCRIPT_DIR/nvim" --headless "+Lazy! sync" +qa
exec "$SCRIPT_DIR/nvim" --headless -S "$SCRIPT_DIR/sync.lua"
